name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.x'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: go get ./...
    - name: Run Unit tests
      run: |
        go test -v -covermode atomic -coverprofile="coverage.out" ./...
        go tool cover -func="coverage.out"

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          go get ./...
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/gordonklaus/ineffassign@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - name: Check format
        run: |
          if gofmt -e -l . >&1 | grep '^'; then
            exit 1
          fi
      - name: Lint with vet
        run: go vet ./...
      - name: Lint with staticcheck
        run: staticcheck ./...
      - name: Lint with ineffassign
        run: ineffassign ./...
      - name: Lint with gocyclo
        run: gocyclo -over 15 .

  examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.x'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: go get ./...
    - name: Build command line tool
      run: go build ./cmd/bbn
    - name: Run CLI examples
      run: |
        ./bbn sample _examples/sprinkler.yml
        ./bbn sample _examples/monty-hall.yml
        ./bbn sample _examples/asia.yml
        ./bbn sample _examples/native-fish.yml
        ./bbn sample _examples/mendel.yml
        ./bbn sample _examples/umbrella.yml
        ./bbn sample _examples/dog-problem.xml
        ./bbn train _examples/fruits.yml _examples/fruits.csv
